# Generated by Django 5.0.3 on 2024-03-13 12:28

import apps.loan.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False,
                 primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(choices=[('0', 'OUTROS'), ('1', 'ATIVO'), ('2', 'QUITADO'), (
                    '3', 'CANCELADO'), ('4', 'EM ATRASO')], max_length=60, verbose_name='Descrição do Empréstimo')),
                ('contracted_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[
                 apps.loan.models.positive_validator], verbose_name='Valor Contratado')),
                ('remaining_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10,
                 null=True, validators=[apps.loan.models.positive_validator], verbose_name='Falta Pagar')),
                ('number_of_installments', models.PositiveIntegerField(
                    verbose_name='Quantidade de Parcelas')),
                ('tax_fees', models.DecimalField(decimal_places=2, max_digits=10, validators=[
                 apps.loan.models.positive_validator], verbose_name='Juros')),
                ('nominal_amount', models.DecimalField(blank=True, decimal_places=2,
                 max_digits=10, null=True, verbose_name='Valor Total a Pagar')),
                ('bank', models.CharField(max_length=20, verbose_name='Banco')),
                ('status', models.CharField(choices=[('0', 'OUTROS'), ('1', 'ATIVO'), ('2', 'QUITADO'), (
                    '3', 'CANCELADO'), ('4', 'EM ATRASO')], verbose_name='Status Empréstimo')),
                ('ip_address', models.GenericIPAddressField(
                    blank=True, null=True, verbose_name='Endereço IP')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                 related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False,
                 primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[
                 apps.loan.models.positive_validator], verbose_name='Valor')),
                ('installment_number', models.PositiveIntegerField(
                    verbose_name='Número Parcela')),
                ('status', models.CharField(choices=[
                 ('0', 'OUTROS'), ('1', 'Ativa'), ('3', 'Paga')], verbose_name='Status Parcela')),
                ('due_date', models.DateField(verbose_name='Data Vencimento')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='installments', to='loan.loan')),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcelas',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False,
                 primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('payment_method', models.CharField(blank=True, choices=[('0', 'OUTROS'), ('1', 'PIX'), ('2', 'BOLETO'), (
                    '3', 'CARTÃO'), ('4', 'TRANSFERÊNCIA'), ('5', 'DINHEIRO')], null=True, verbose_name='Metodo de Pagamento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[
                 apps.loan.models.positive_validator], verbose_name='Valor Transação')),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='payment_installments', to='loan.installment')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'ordering': ['-created_at'],
            },
        ),
    ]
