# Generated by Django 5.0.3 on 2024-03-14 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_ips_remove_loan_ip_address_alter_loan_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ips',
            new_name='LoanIp',
        ),
        migrations.AlterModelOptions(
            name='loanip',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ip', 'verbose_name_plural': 'Ips'},
        ),
    ]
