# Generated by Django 5.0.3 on 2024-03-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_rename_ips_loanip_alter_loanip_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Outros'), (1, 'Ativa'), (2, 'Paga')], verbose_name='Status Parcela'),
        ),
    ]
