# Generated by Django 5.0.3 on 2024-03-14 19:25

import apps.loan.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_alter_installment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='client',
            field=models.CharField(default=1, max_length=60, verbose_name='Cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loan',
            name='tax_fees',
            field=models.DecimalField(decimal_places=10, max_digits=20, validators=[apps.loan.models.positive_validator], verbose_name='Juros'),
        ),
    ]
