# Generated by Django 5.0.3 on 2024-03-14 19:28

import apps.loan.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_loan_client_alter_loan_tax_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='tax_fees',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[apps.loan.models.positive_validator], verbose_name='Juros'),
        ),
    ]
